<a href="https://colab.research.google.com/github/giuseppefutia/machine-learning/blob/master/gcn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Learning Guide to Graph Convolutional Networks

* Describe the concept of Deep Learning on Graphs.
* Describe the 3 types of Graph Deep Learning methods.
* Describe in which category resides the Graph Convolutional Networks among the previous ones.

Sources: 
* A Beginner's Guide to Graph Analytics and Deep Learning: https://skymind.ai/wiki/graph-analysis
* https://arxiv.org/abs/1812.04202

## Graph Data Features and Issues

* Irregular domain.
    
* Diverse structures and tasks.

* Scalability and parallelization.
  
* Interdiscipline.

Sources: 
 * Source: Youtube: https://www.youtube.com/watch?v=4pasBJ_hPMQ.
    * Introduce the concept of non-euclidean data.
         * https://arxiv.org/pdf/1611.08097.pdf
         * https://www.youtube.com/watch?v=b187J4ndZWY







## Notation and Representation
In this section we provide some notation in order to describe a graph and we describe how we can represent graphs using matrices.

### Graph Notation
TODO

### How to Represent Graph Using Matrices
Machine learning algorithms are able to process data in the form of matrices. For such reasons, we need to understand how we can represent graph using matrices.

Consider the following graph example:

![Graph example](http://graphonline.ru/tmp/saved/RF/RFAOxGXmjawkuiWO.png =300x)

We can represent this graph using the following matrices.

#### Incidence Matrix
An incidence matrix is a matrix that shows the relationship between two classes of objects (nodes and objects). Incidence matrices can describe directed and undirected graphs.

In case of an undirected graph (like our example), we adopt an unoriented incidecence matrix is a $n × m$ matrix $B$, where $n$ and $m$ are the numbers of vertices and edges respectively, such that $B_{i,j} = 1$ if the vertex $v_i$ and edge $e_j$ are incident and 0 otherwise.

The incidence matrix of our graph example is the following:

$\begin{bmatrix}
  1. & 1. & 1. & 0 \\
  1. & 0. & 0. & 0 \\
  0. & 0. & 1. & 1 \\
  0. & 1. & 0. & 1 \\
\end{bmatrix}$

#### Adjacency Matrix

An adjacency matrix is a square matrix used to represent a finite graph. The elements of the matrix indicate whether pairs of vertices are adjacent or not in the graph. 

If the graph is undirected, the adjacency matrix is symmetric. The adjacency matrix of our graph example is the following:

$\begin{bmatrix}
  0. & 1. & 1. & 1 \\ 
  1. & 0. & 0. & 0 \\ 
  1. & 0. & 0. & 1 \\ 
  1. & 0. & 1. & 0 \\ 
\end{bmatrix}$

#### Degree Matrix
The degree matrix is a diagonal matrix which contains information about the degree of each vertex—that is, the number of edges attached to each vertex.

The degree is used together with the adjacency matrix to construct the Laplacian matrix of a graph (that we explore in the following section). The degree matrix of our graph example is the following: 

$\begin{bmatrix}
  3. & 0. & 0. & 0 \\ 
  0. & 1. & 0. & 0 \\ 
  0. & 0. & 2. & 0 \\ 
  0. & 0. & 0. & 2 \\ 
\end{bmatrix}$

#### Laplacian Matrix
The Laplacian matrix, sometimes called admittance matrix, Kirchhoff matrix or discrete Laplacian, is a matrix representation of a graph. It can be used to calculate the number of spanning trees for a given graph and to to construct low dimensional embeddings, which can be useful for a variety of machine learning applications.

Given a simple graph $G$ with $n$ vertices, its Laplacian matrix ${\textstyle L_{n\times n}} $ is defined as:

${\displaystyle L=D-A,}$ where $D$ is the degree matrix and $A$ is the adjacency matrix of the graph.

Let's see the representation of the Laplacian matrix using numpy: 


In [6]:
import numpy as np

# Adjacency Matrix - Size (4,4)
A = np.matrix([
    [0, 1, 1, 1],
    [1, 0, 0, 0], 
    [1, 0, 0, 1],
    [1, 0, 1, 0]],
    dtype=float
)
print()
print()
print('Adjacency Matrix')
print(A)

# Degree Matrix - Size (4,4)
D = np.matrix([
    [3, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 2]],
    dtype=float
)

print()
print()
print('Degree Matrix')
print(D)

# The Degree Matrix can be computed from the Adjacency Matrix
D_from_A = np.array(np.sum(A, axis=0))[0]
D_from_A = np.matrix(np.diag(D_from_A))

print()
print()
print('Computed Degree Matrix from Adjacency one')
print(D_from_A)


# Laplacian matrix - Size (4,4)
L = D-A

print()
print()
print('Laplacian Matrix')
print(L)





Adjacency Matrix
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]


Degree Matrix
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Computed Degree Matrix from Adjacency one
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Laplacian Matrix
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


Through the observation of the laplacian matrix of a simple graph (no loop edges for each node), we can notice the following features:

* if $i=j$, the value of the cell is equal to $deg(v_i)$
* if $i \neq j$, and $v_i$ is adjacent to $v_j$, the value is equal to $-1$
* otherwise, $0$

We can also obtain the **symmetric normalized laplacian matrix**, that is defined as follows:

$L^{sym} := D^{-1/2}LD^{-1/2}=I-D^{-1/2}AD^{-1/2}$

Let's compute the symmetric normalized laplacian using numpy:

In [10]:
import numpy as np

# Adjacency Matrix - Size (4,4)
A = np.matrix([
    [0, 1, 1, 1],
    [1, 0, 0, 0], 
    [1, 0, 0, 1],
    [1, 0, 1, 0]],
    dtype=float
)

print()
print()
print('Adjacency Matrix')
print(A)

# The Degree Matrix can be computed from the Adjacency Matrix
D_from_A = np.array(np.sum(A, axis=0))[0]
D_from_A = np.matrix(np.diag(D_from_A))

print()
print()
print('Computed Degree Matrix from Adjacency one')
print(D_from_A)

# Laplacian matrix - Size (4,4)
L = D_from_A-A

print()
print()
print('Laplacian Matrix')
print(L)

# Inverse Degree Matrix
D_hat = np.sqrt(D_from_A)

L_sym_1 = D_hat * L * D_hat

print()
print()
print('L_sym_1')
print(L_sym_1)



Adjacency Matrix
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]]


Computed Degree Matrix from Adjacency one
[[3. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Laplacian Matrix
[[ 3. -1. -1. -1.]
 [-1.  1.  0.  0.]
 [-1.  0.  2. -1.]
 [-1.  0. -1.  2.]]


L_sym_1
[[ 9.         -1.73205081 -2.44948974 -2.44948974]
 [-1.73205081  1.          0.          0.        ]
 [-2.44948974  0.          4.         -2.        ]
 [-2.44948974  0.         -2.          4.        ]]


TODO: Understanding normalized Laplacian Matrix:

* https://www.youtube.com/playlist?list=PLkpN8cIB_rZFgZK6WLZu7n88c6cjgE2Kw

* https://math.stackexchange.com/questions/1113467/why-laplacian-matrix-need-normalization-and-how-come-the-sqrt-of-degree-matrix

* http://www.cs.yale.edu/homes/spielman/PAPERS/SGTChapter.pdf

* https://people.orie.cornell.edu/dpw/orie6334/lecture7.pdf

* https://people.orie.cornell.edu/mru8/orie4741/lectures/spectral.pdf

* https://people.orie.cornell.edu/dpw/orie6334/index.html

* https://blog.xrds.acm.org/2014/05/the-geometric-origins-of-spectral-graph-theory/

* https://lucatrevisan.wordpress.com/2016/02/01/cs294-lecture-2-basics-of-spectral-graph-theory/

## Deepening on GCN

Sources: 
* https://www.youtube.com/playlist?list=PLLyXKRG8-SS0cggcM_xWby7HQHOnECVuD

### Numpy Implementation - Forward Propagation
Sources: https://towardsdatascience.com/how-to-do-deep-learning-on-graphs-with-graph-convolutional-networks-7d2250723780

In [0]:
import numpy as np

# Adjacency Matrix - Size (4,4).
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)
print('Adjacency Matrix')
print(A)
print()

# Feature Matrix - Size (4.2).
X = np.matrix([
            [i, -i]
            for i in range(A.shape[0])
        ], dtype=float)

print('Feature Matrix')
print(X)
print()

# Applying the propagation rule to obtain an embedding representation of nodes
# from the adjacency matrix. With the following operation, we represent each
# node of the graph with two elements (because of the dimension of the feature matrix).
L1 = A * X
print ('Forward rule')
print(L1)
print()

# Note: The representation of each node (each row) is now a sum of its neighbors
# features. In other words, the graph convolutional layer represents each node 
# as an aggregate of its neighborhood.

# The aggregated representation of a node does not include its own features, for
# these reasons we need to include a self-loop. To compute this self-loop, we
# need to add an identity matrix to the adjacency matrix before applying the
# propagation rules.
I = np.matrix(np.eye(A.shape[0]))
A_hat = A + I
L1 = A_hat * W1
print ('Forward rule with the first loop')
print(L1)
print()

# To avoid vanishing and explosion gradients issues, we need to normalize the
# feature representation of data. We can perform this normalization multiplying
# the adjancecy matrix with the inverse degree matrix. The degree matrix is
# computed summing the values in each adjacency matrix row and then put this
# values in a diagonal matrix

D = np.array(np.sum(A, axis=0))[0]
print('Degree Matrix starting from the Adjacency Matrix')
print(D)
print()
D = np.matrix(np.diag(D))
print('Inverse of Degree Matrix starting from the Adjacency Matrix')
print(D**-1)
print()

# In order to train the network, we need to define a matrix weight
W = np.matrix([
    [1, -1],
    [-1, 1]
])
print('Weight Matrix')
print(W)
print()

# Before comple the propagation we need to create the degree matrix from A_hat
# and not simply A. After that you need to compute the entire propagation
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))
forward = D_hat**-1 * A_hat * X * W
print('Forward computation')
print(forward)
print()


### Forward Propagation Using Real Data
Source: https://towardsdatascience.com/how-to-do-deep-learning-on-graphs-with-graph-convolutional-networks-7d2250723780 

### Pytorch Implementation - Semi-Supervised Learning with Spectral Graph Convolutions
Source: https://towardsdatascience.com/how-to-do-deep-learning-on-graphs-with-graph-convolutional-networks-62acf5b143d0