<a href="https://colab.research.google.com/github/giuseppefutia/ml/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Tutorial

To install Pytorch, you can run the following command:

In [0]:
import torch

Some basic operations:

In [2]:
x = torch.randn(4,4)
print(x)
z = x.view(8, -1)
print(z)
print(z.size())

tensor([[-0.1649, -1.2644, -0.8343,  1.5186],
        [-1.3898,  0.7941, -1.0053,  0.0614],
        [-2.1090, -1.4727, -1.3148, -0.3132],
        [ 0.9935, -1.0072,  0.9316, -1.0751]])
tensor([[-0.1649, -1.2644],
        [-0.8343,  1.5186],
        [-1.3898,  0.7941],
        [-1.0053,  0.0614],
        [-2.1090, -1.4727],
        [-1.3148, -0.3132],
        [ 0.9935, -1.0072],
        [ 0.9316, -1.0751]])
torch.Size([8, 2])


## Cuda Tensors

In [3]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  print(device)
else:
  print('cuda not available')

cuda not available


## Autograd

In [4]:
print('Create a tensor with requires_grad=True')
x = torch.ones(2, 2, requires_grad=True)
print(x)
print()
print()

print('When I compute any operation on a Tensor, and I have defined requires_grad=True, a gradient function is associated to the new Tensor')
y = x+2
print(y)
print(y.grad_fn)
print()
print()

print('More operations: multiplications and means')
z = y * y * 3
out = z.mean()
print(z)
print(out)
print()
print()



Create a tensor with requires_grad=True
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


When I compute any operation on a Tensor, and I have defined requires_grad=True, a gradient function is associated to the new Tensor
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


More operations: multiplications and means
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)




## Gradients

In [0]:
out.backward()

Print gradients d(out)/dx

In [6]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
