<a href="https://colab.research.google.com/github/giuseppefutia/mlog/blob/master/rgcn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A step-by-step guide to build R-GCN in Pytorch

In this notebook I describe how to develop Relational Graph Convolutional Networks (R-GCNs) of the link-prediction task within Knowledge Graphs. For more information on R-GCNs we suggest the following article:


*   Schlichtkrull, M., Kipf, T. N., Bloem, P., van den Berg, R., Titov, I., & Welling, M. (2018, June). [Modeling relational data with graph convolutional networks](https://link.springer.com/chapter/10.1007/978-3-319-93417-4_38). In European Semantic Web Conference (pp. 593-607). Springer, Cham.

I take some parts of this article in order to describe and explain the source code deployed in this notebook. The main part of this code is inspired by the Deep Graph Library (DGL - https://www.dgl.ai/), that is a python package built to ease deep learning on graph, on top of existing deep learning frameworks. 


# Install required libraries

In [1]:
!pip install dgl
!pip install rdflib
!pip install torch

# Import libraries

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = torch.device("cpu")
if torch.cuda.is_available(): # Try to use GPU if available
  device = torch.device('cuda')

print('Your device is ' + str(device))

Your device is cuda


# Utils

Most code of the Utils section is adapted from authors' implementation of RGCN link prediction:
https://github.com/MichSchli/RelationPrediction.

In the utils section are implemented functions that are useful for the following steps:


1.   Compute the adjacency matrix of the knowledge graph and the degrees of each node.
2.   Reduce the training time sampling the edge neighborhood.
3.   Perform the negative sampling to further reduce the training time.





## Functions for Graph Sampling and Building

In [0]:
def get_adj_and_degrees(num_nodes, triplets):
    """ 
    Get adjacency list and degrees of the graph
    
    Arguments:
    
    num_nodes -- (int) number of nodes in the graph
    triplets -- (matrix) size(number of training samples, 3). Each row of the
                matrix is in the form: [subject_id, relation_id, object_id]
    
    Returns:
    
    adj_list -- (structure) size(number of nodes, node degree)
    degrees -- (vector) size(, number of nodes). Each element of the vector is
               filled with the degree of the node.
    
    """
    adj_list = [[] for _ in range(num_nodes)]
    for i,triplet in enumerate(triplets):
        adj_list[triplet[0]].append([i, triplet[2]])
        adj_list[triplet[2]].append([i, triplet[0]])

    degrees = np.array([len(a) for a in adj_list])
    adj_list = [np.array(a) for a in adj_list]
    return adj_list, degrees

  
def sample_edge_neighborhood(adj_list, degrees, n_triplets, sample_size):
    """ 
    Edge neighborhood sampling to reduce graph size for training purposes
    
    Arguments:
    
    adj_list -- (structure) size(number of nodes, node degree)
    degrees -- (vector) size(, number of nodes). Each element of the vector is
               filled with the degree of the node
    n_triplets -- (int) number of triples in the training data
    sample_size -- (int) number of edges to sample in each iteration (parameter)
    
    Returns:
    
    edges -- list of edge indexes as result of the sampling process
    """

    edges = np.zeros((sample_size), dtype=np.int32)

    # Initialization for sampling of nodes
    sample_counts = np.array([d for d in degrees])
    picked = np.array([False for _ in range(n_triplets)])
    seen = np.array([False for _ in degrees])

    for i in range(0, sample_size):
        weights = sample_counts * seen

        if np.sum(weights) == 0:
            weights = np.ones_like(weights)
            weights[np.where(sample_counts == 0)] = 0

        probabilities = (weights) / np.sum(weights)
        
        # Choose vertex according to the computed probabilities
        # The number of chosen vertices is based on the sample size parameter
        chosen_vertex = np.random.choice(np.arange(degrees.shape[0]),
                                         p=probabilities)
        # Store all edges and nodes linked to the chosen vertex
        chosen_adj_list = adj_list[chosen_vertex]
        seen[chosen_vertex] = True
        
        # On the basis of the chosen vertex, randomly choose the edge and pick it up
        # from the adjacency list and store its value in the edge number
        chosen_edge = np.random.choice(np.arange(chosen_adj_list.shape[0]))
        chosen_edge = chosen_adj_list[chosen_edge]
        edge_number = chosen_edge[0]
        
        # If the edge has benn already picked, 
        # choose another one according to the same principles
        while picked[edge_number]:
            chosen_edge = np.random.choice(np.arange(chosen_adj_list.shape[0]))
            chosen_edge = chosen_adj_list[chosen_edge]
            edge_number = chosen_edge[0]
        
        edges[i] = edge_number
        other_vertex = chosen_edge[1]
        picked[edge_number] = True
        sample_counts[chosen_vertex] -= 1
        sample_counts[other_vertex] -= 1
        seen[other_vertex] = True
        
        # Return all edges from the sampling process
    return edges

  
def generate_sampled_graph_and_labels(triplets, sample_size, split_size,
                                      num_rels, adj_list, degrees,
                                      negative_rate):
    """
    Get training graph and signals
    First perform edge neighborhood sampling on graph, then perform negative
    sampling to generate negative samples
    
    Arguments:
    
    triplets -- (matrix) size (num of triples in the training, 3)
    sample_size -- (int) number of nodes to take as samples
    split_size -- (int) parameter to split the graph from (0 to 1)
    num_rels -- (int) number of unique relations in the training set
    adj_list -- (list) size(number of nodes, node degree)
    degrees -- (vector) size(, number of nodes).
    negative_rate -- (parameter)
    
    Returns:
    g -- DGL graph
    uniq_v -- (vector) unique nodes
    rel -- (vector) relations
    norm -- (vector) normalized degree values of each node
    samples -- (matrix) triple samples considering positive and negative samples
    labels -- (vector) size(,positive + negative samples). The value of each element
              is 1 for positive samples and 0 for negative samples.
    """
    
    # Perform edge neighbor sampling to take a subset of edges
    edges = sample_edge_neighborhood(adj_list, degrees, len(triplets),
                                     sample_size)

    # Relabel nodes to have consecutive node ids
    edges = triplets[edges] 
    src, rel, dst = edges.transpose()
    # Get unique vertices: such vertices are the result of the sampling 
    # At the end of this process, we obtain an array of new triplets:
    # we use as node indexes the values of the array to reconstruct
    # the original src and dst
    uniq_v, edges = np.unique((src, dst), return_inverse=True)
    src, dst = np.reshape(edges, (2, -1))
    relabeled_edges = np.stack((src, rel, dst)).transpose()

    # Negative sampling
    samples, labels = negative_sampling(relabeled_edges, len(uniq_v),
                                        negative_rate)

    # Further split graph, only half of the edges will be used as graph
    # structure, while the rest half is used as unseen positive samples
    # The graph is splitted in the dimension split_size, picking up randomly
    # values between 0 and sample_size. 
    # According to these random values, I create the new src, dst, and rel arrays
    split_size = int(sample_size * split_size)
    graph_split_ids = np.random.choice(np.arange(sample_size),
                                       size=split_size, replace=False)
    src = src[graph_split_ids]
    dst = dst[graph_split_ids]
    rel = rel[graph_split_ids]
   
    # Build DGL graph
    # The number of nodes is equal to unique nodes after the sampling process
    # The number of edges is equal to src*2, because we consider in and out edges
    print("# sampled nodes: {}".format(len(uniq_v)))
    print("# sampled edges: {}".format(len(rel) * 2))
    g, rel, norm = build_graph_from_triplets(len(uniq_v), num_rels,
                                             (src, rel, dst))
    
    return g, uniq_v, rel, norm, samples, labels

  
def comp_deg_norm(g):
    """
    Apply a normalization to the values of input degree for each node
    
    Arguments:
    
    g -- DGL Graph
    
    Returns:
    
    norm -- np.array of normalized degree values - 1 X num of nodes
    """
    in_deg = g.in_degrees(range(g.number_of_nodes())).float().numpy()
    norm = 1.0 / in_deg
    # If the in_deg is 0, the result of normalization is inf (put 0 in this case)
    norm[np.isinf(norm)] = 0

    return norm

  
def build_graph_from_triplets(num_nodes, num_rels, triplets):
    """ 
    Create a DGL graph. The graph is bidirectional because RGCN authors
    use reversed relations. This function also generates edge type and
    normalization factor (reciprocal of node incoming degree)
    
    Arguments:
    
    num_nodes -- Number of nodes (result of the sampling)
    num_rels -- Number of relations (doubled compared to the original ones)
    triplets -- Three different arrays: src, rel, dst (result of the splitted graph)
    
    Returns:
    
    g -- High-level representation of the graph created using the DGL library
    rel -- (vector) vector of all relations
    norm -- (vector) normalized-degree of nodes
    """
    g = dgl.DGLGraph()
    g.add_nodes(num_nodes)
    src, rel, dst = triplets
    
    # The bidirectional graph is created (nodes are doubled)
    src, dst = np.concatenate((src, dst)), np.concatenate((dst, src))
    
    # The relations are doubled adding the number of different relations 
    rel = np.concatenate((rel, rel + num_rels))
    
    # Create the edges array
    edges = sorted(zip(dst, src, rel))    
    dst, src, rel = np.array(edges).transpose() # 3 x Num of nodes
    g.add_edges(src, dst)
    
    norm = comp_deg_norm(g)
    print("# nodes: {}, # edges: {}".format(num_nodes, len(src)))
    
    return g, rel, norm

  
def build_test_graph(num_nodes, num_rels, edges):
    src, rel, dst = edges.transpose()
    print("Test graph:")
    return build_graph_from_triplets(num_nodes, num_rels, (src, rel, dst))

  
def negative_sampling(pos_samples, num_entity, negative_rate):
    """
    Apply negative sampling
    
    Arguments:
    
    pos_samples -- Relabeled edges according to the sampling process
    num_entity -- Number of entities
    negative_rate -- Negative rate parameter (default 10)
    
    Returns:
    np.array, labels -- np.array contains a concatenation of positive samples
                        and negative samples. 
                        labels is an array where elements are equal to 1 for 
                        positive samples and 0 for negative samples
    """
    size_of_batch = len(pos_samples)
    num_to_generate = size_of_batch * negative_rate
    
    # Construct an array of negative samples by repeating 
    # the positive samples for the negative_rate value.
    # Then, I create a label array to perform the logistic regression related to
    # the negative sampling. I initialize the first size_of_batch of labels to 1
    # and the other values are equal to 0.
    neg_samples = np.tile(pos_samples, (negative_rate, 1))        
    labels = np.zeros(size_of_batch * (negative_rate + 1), dtype=np.float32)
    labels[: size_of_batch] = 1
    
    # Create negative samples replacing the subject or the object according
    # to the random probability generated in choices
    # 
    # If the positive samples are the following: 
    # [[1540  154 2254]
    # [ 510  193 1540]
    # [1540   55 1269]...]
    #
    # The negative samples will be the following:
    # [[1540  154 1750]
    #  [1051  193 1540]
    #  [85   55 1269]...]
    #
    # In other words we generate wrong triples
    values = np.random.randint(num_entity, size=num_to_generate)
    choices = np.random.uniform(size=num_to_generate)
    subj = choices > 0.5
    obj = choices <= 0.5
    neg_samples[subj, 0] = values[subj]
    neg_samples[obj, 2] = values[obj]
    
    return np.concatenate((pos_samples, neg_samples)), labels

## Functions for Evaluation

In [0]:
def sort_and_rank(score, target):
    _, indices = torch.sort(score, dim=1, descending=True)
    indices = torch.nonzero(indices == target.view(-1, 1))
    indices = indices[:, 1].view(-1)
    return indices

  
def perturb_and_get_rank(embedding, w, a, r, b, num_entity, batch_size=100):
    """ 
    Perturb one element in the triplets
    
    """
    n_batch = (num_entity + batch_size - 1) // batch_size
    ranks = []
    for idx in range(n_batch):
        print("batch {} / {}".format(idx, n_batch))
        batch_start = idx * batch_size
        batch_end = min(num_entity, (idx + 1) * batch_size)
        batch_a = a[batch_start: batch_end]
        batch_r = r[batch_start: batch_end]
        emb_ar = embedding[batch_a] * w[batch_r]
        emb_ar = emb_ar.transpose(0, 1).unsqueeze(2) # size: D x E x 1
        emb_c = embedding.transpose(0, 1).unsqueeze(1) # size: D x 1 x V
        # out-prod and reduce sum
        out_prod = torch.bmm(emb_ar, emb_c) # size D x E x V
        score = torch.sum(out_prod, dim=0) # size E x V
        score = torch.sigmoid(score)
        target = b[batch_start: batch_end]
        ranks.append(sort_and_rank(score, target))
    return torch.cat(ranks)


# return MRR (raw), and Hits @ (1, 3, 10)
def evaluate(test_graph, model, test_triplets, num_entity, hits=[], eval_bz=100):
    with torch.no_grad():
        embedding, w = model.evaluate(test_graph)
        s = test_triplets[:, 0]
        r = test_triplets[:, 1]
        o = test_triplets[:, 2]

        # perturb subject
        ranks_s = perturb_and_get_rank(embedding, w, o, r, s, num_entity, eval_bz)
        # perturb object
        ranks_o = perturb_and_get_rank(embedding, w, s, r, o, num_entity, eval_bz)

        ranks = torch.cat([ranks_s, ranks_o])
        ranks += 1 # change to 1-indexed

        mrr = torch.mean(1.0 / ranks.float())
        print("MRR (raw): {:.6f}".format(mrr.item()))

        for hit in hits:
            avg_count = torch.mean((ranks <= hit).float())
            print("Hits (raw) @ {}: {:.6f}".format(hit, avg_count.item()))
    return mrr.item()

# R-GCN Layers

I describe the implementation of a R-GCN Layer, starting from an abstract class. 

In [0]:
import torch.nn as nn

class RGCNLayer(nn.Module):
  '''
  The abstract layer of a R-GCN is built starting from the following parameters:
  in_feat --  
  out_feat --
  bias --
  activation --
  self_loop --
  dropout --
  '''
  def __init__(self, in_feat, out_feat, bias=None, activation=None,
                 self_loop=False, dropout=0.0):
    
    super(RGCNLayer, self).__init__()
        
    self.bias = bias
    self.activation = activation
    self.self_loop = self_loop

    if self.bias == True:
        self.bias = nn.Parameter(torch.Tensor(out_feat))
        nn.init.xavier_uniform_(self.bias,
                                gain=nn.init.calculate_gain('relu'))

    # weight for self loop
    if self.self_loop:
        self.loop_weight = nn.Parameter(torch.Tensor(in_feat, out_feat))
        nn.init.xavier_uniform_(self.loop_weight,
                                gain=nn.init.calculate_gain('relu'))

    if dropout:
        self.dropout = nn.Dropout(dropout)
    else:
        self.dropout = None

  # define how propagation is done in subclass
  def propagate(self, g):
      raise NotImplementedError

  def forward(self, g):
      if self.self_loop:
          loop_message = torch.mm(g.ndata['h'], self.loop_weight)
          if self.dropout is not None:
              loop_message = self.dropout(loop_message)

      self.propagate(g)

      # apply bias and activation
      node_repr = g.ndata['h']
      if self.bias:
          node_repr = node_repr + self.bias
      if self.self_loop:
          node_repr = node_repr + loop_message
      if self.activation:
          node_repr = self.activation(node_repr)

      g.ndata['h'] = node_repr

**Tips**:


*   List item
*   List item



## Basis Layer

In [0]:
class RGCNBasisLayer(RGCNLayer):
    
    def __init__(self, in_feat, out_feat, num_rels, num_bases=-1, bias=None,
                 activation=None, is_input_layer=False):
        
        super(RGCNBasisLayer, self).__init__(in_feat, out_feat, bias, activation)
        
        self.in_feat = in_feat
        self.out_feat = out_feat
        self.num_rels = num_rels
        self.num_bases = num_bases
        self.is_input_layer = is_input_layer
        if self.num_bases <= 0 or self.num_bases > self.num_rels:
            self.num_bases = self.num_rels

        # add basis weights
        self.weight = nn.Parameter(torch.Tensor(self.num_bases, self.in_feat,
                                                self.out_feat))
        if self.num_bases < self.num_rels:
            # linear combination coefficients
            self.w_comp = nn.Parameter(torch.Tensor(self.num_rels,
                                                    self.num_bases))
        nn.init.xavier_uniform_(self.weight, gain=nn.init.calculate_gain('relu'))
        if self.num_bases < self.num_rels:
            nn.init.xavier_uniform_(self.w_comp,
                                    gain=nn.init.calculate_gain('relu'))

    def propagate(self, g):
        if self.num_bases < self.num_rels:
            # generate all weights from bases
            weight = self.weight.view(self.num_bases,
                                      self.in_feat * self.out_feat)
            weight = torch.matmul(self.w_comp, weight).view(
                                    self.num_rels, self.in_feat, self.out_feat)
        else:
            weight = self.weight

        if self.is_input_layer:
            def msg_func(edges):
                # for input layer, matrix multiply can be converted to be
                # an embedding lookup using source node id
                embed = weight.view(-1, self.out_feat)
                index = edges.data['type'] * self.in_feat + edges.src['id']
                return {'msg': embed.index_select(0, index) * edges.data['norm']}
        else:
            def msg_func(edges):
                w = weight.index_select(0, edges.data['type'])
                msg = torch.bmm(edges.src['h'].unsqueeze(1), w).squeeze()
                msg = msg * edges.data['norm']
                return {'msg': msg}

        g.update_all(msg_func, fn.sum(msg='msg', out='h'), None)

**Tips**


*   List item
*   List item




 ## Block Layer

In [0]:
class RGCNBlockLayer(RGCNLayer):
    
    def __init__(self, in_feat, out_feat, num_rels, num_bases, bias=None,
                 activation=None, self_loop=False, dropout=0.0):
        
        super(RGCNBlockLayer, self).__init__(in_feat, out_feat, bias,
                                             activation, self_loop=self_loop,
                                             dropout=dropout)
        self.num_rels = num_rels
        self.num_bases = num_bases
        assert self.num_bases > 0

        self.out_feat = out_feat
        self.submat_in = in_feat // self.num_bases
        self.submat_out = out_feat // self.num_bases

        # assuming in_feat and out_feat are both divisible by num_bases
        self.weight = nn.Parameter(torch.Tensor(
            self.num_rels, self.num_bases * self.submat_in * self.submat_out))
        nn.init.xavier_uniform_(self.weight, gain=nn.init.calculate_gain('relu'))

    def msg_func(self, edges):
        weight = self.weight.index_select(0, edges.data['type']).view(
                    -1, self.submat_in, self.submat_out)
        node = edges.src['h'].view(-1, 1, self.submat_in)
        msg = torch.bmm(node, weight).view(-1, self.out_feat)
        return {'msg': msg}

    def propagate(self, g):
        g.update_all(self.msg_func, fn.sum(msg='msg', out='h'), self.apply_func)

    def apply_func(self, nodes):
        return {'h': nodes.data['h'] * nodes.data['norm']}

**Tips**


*   List item
*   List item




# R-GCN Model

In [0]:
class BaseRGCN(nn.Module):
    def __init__(self, num_nodes, h_dim, out_dim, num_rels, num_bases=-1,
                 num_hidden_layers=1, dropout=0, use_cuda=False):
        super(BaseRGCN, self).__init__()
        self.num_nodes = num_nodes
        self.h_dim = h_dim
        self.out_dim = out_dim
        self.num_rels = num_rels
        self.num_bases = num_bases
        self.num_hidden_layers = num_hidden_layers
        self.dropout = dropout
        self.use_cuda = use_cuda

        # create rgcn layers
        self.build_model()

        # create initial features
        self.features = self.create_features()

    def build_model(self):
        self.layers = nn.ModuleList()
        # i2h
        i2h = self.build_input_layer()
        if i2h is not None:
            self.layers.append(i2h)
        # h2h
        for idx in range(self.num_hidden_layers):
            h2h = self.build_hidden_layer(idx)
            self.layers.append(h2h)
        # h2o
        h2o = self.build_output_layer()
        if h2o is not None:
            self.layers.append(h2o)

    # initialize feature for each node
    def create_features(self):
        return None

    def build_input_layer(self):
        return None

    def build_hidden_layer(self, idx):
        raise NotImplementedError

    def build_output_layer(self):
        return None

    def forward(self, g):
        if self.features is not None:
            g.ndata['id'] = self.features
        for layer in self.layers:
            layer(g)
        return g.ndata.pop('h')

# Link prediction stage

In [0]:
import time
import torch.nn.functional as F
import dgl
import dgl.function as fn
from dgl.contrib.data import load_data

class EmbeddingLayer(nn.Module):
    def __init__(self, num_nodes, h_dim):
        super(EmbeddingLayer, self).__init__()
        self.embedding = torch.nn.Embedding(num_nodes, h_dim)

    def forward(self, g):
        node_id = g.ndata['id'].squeeze()
        g.ndata['h'] = self.embedding(node_id)

class RGCN(BaseRGCN):
    def build_input_layer(self):
        return EmbeddingLayer(self.num_nodes, self.h_dim)

    def build_hidden_layer(self, idx):
        act = F.relu if idx < self.num_hidden_layers - 1 else None
        
        return RGCNBlockLayer(self.h_dim, self.h_dim, self.num_rels, self.num_bases,
                         activation=act, self_loop=True, dropout=self.dropout)

class LinkPredict(nn.Module):
    def __init__(self, in_dim, h_dim, num_rels, num_bases=-1,
                 num_hidden_layers=1, dropout=0, use_cuda=False, reg_param=0):
        super(LinkPredict, self).__init__()
        self.rgcn = RGCN(in_dim, h_dim, h_dim, num_rels * 2, num_bases,
                         num_hidden_layers, dropout, use_cuda)
        self.reg_param = reg_param
        self.w_relation = nn.Parameter(torch.Tensor(num_rels, h_dim))
        nn.init.xavier_uniform_(self.w_relation,
                                gain=nn.init.calculate_gain('relu'))

    def calc_score(self, embedding, triplets):
        # DistMult
        s = embedding[triplets[:,0]]
        r = self.w_relation[triplets[:,1]]
        o = embedding[triplets[:,2]]
        score = torch.sum(s * r * o, dim=1)
        return score

    def forward(self, g):
        return self.rgcn.forward(g)

    def evaluate(self, g):
        # get embedding and relation weight without grad
        embedding = self.forward(g)
        return embedding, self.w_relation

    def regularization_loss(self, embedding):
        return torch.mean(embedding.pow(2)) + torch.mean(self.w_relation.pow(2))

    def get_loss(self, g, triplets, labels):
        # triplets is a list of data samples (positive and negative)
        # each row in the triplets is a 3-tuple of (source, relation, destination)
        embedding = self.forward(g)
        score = self.calc_score(embedding, triplets)
        predict_loss = F.binary_cross_entropy_with_logits(score, labels)
        reg_loss = self.regularization_loss(embedding)
        return predict_loss + self.reg_param * reg_loss

## Settings

Default values:


```
args = {'dropout': 0.2,
        'n_hidden': 500,
        'gpu': 1,
        'lr': 1e-2,
        'n_bases': 100,
        'n_layers': 2,
        'n_epochs': 6000,
        'dataset': 'FB15k-237',
        'eval_batch_size': 500,
        'regularization': 0.01,
        'grad_norm': 1.0,
        'graph_batch_size': 30000,
        'graph_split_size': 0.5,
        'negative_sample': 10,
        'evaluate_every': 500}
```



In [0]:
args = {'dropout': 0.2,
        'n_hidden': 500,
        'gpu': 1,
        'lr': 1e-2,
        'n_bases': 100,
        'n_layers': 2,
        'n_epochs': 10,
        'dataset': 'FB15k-237',
        'eval_batch_size': 500,
        'regularization': 0.01,
        'grad_norm': 1.0,
        'graph_batch_size': 3000,
        'graph_split_size': 0.5,
        'negative_sample': 10,
        'evaluate_every': 10}

## Scripts for running

In [11]:
# load graph data
data = load_data(args['dataset'])
num_nodes = data.num_nodes
train_data = data.train
valid_data = data.valid
test_data = data.test
num_rels = data.num_rels

# check cuda
use_cuda = args['gpu'] >= 0 and torch.cuda.is_available()
if use_cuda:
    torch.device('cuda')

# create model
model = LinkPredict(num_nodes,
                    args['n_hidden'],
                    num_rels,
                    num_bases=args['n_bases'],
                    num_hidden_layers=args['n_layers'],
                    dropout=args['dropout'],
                    use_cuda=use_cuda,
                    reg_param=args['regularization'])

# validation and testing triplets
valid_data = torch.LongTensor(valid_data)
test_data = torch.LongTensor(test_data)

# build test graph
test_graph, test_rel, test_norm = build_test_graph(
    num_nodes, num_rels, train_data)
test_deg = test_graph.in_degrees(
            range(test_graph.number_of_nodes())).float().view(-1,1)
test_node_id = torch.arange(0, num_nodes, dtype=torch.long).view(-1, 1)
test_rel = torch.from_numpy(test_rel).view(-1, 1)
test_norm = torch.from_numpy(test_norm).view(-1, 1)
test_graph.ndata.update({'id': test_node_id, 'norm': test_norm})
test_graph.edata['type'] = test_rel

if use_cuda:
    model.cuda()

# build adj list and calculate degrees for sampling
adj_list, degrees = get_adj_and_degrees(num_nodes, train_data)

# optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=args['lr'])

model_state_file = 'model_state.pth'
forward_time = []
backward_time = []
loss_values = []
train_start = time.time()

# training loop
print("start training...")

epoch = 0
best_mrr = 0
while True:
    model.train()
    epoch += 1

    # perform edge neighborhood sampling to generate training graph and data
    g, node_id, edge_type, node_norm, data, labels = \
        generate_sampled_graph_and_labels(
            train_data, args['graph_batch_size'], args['graph_split_size'],
            num_rels, adj_list, degrees, args['negative_sample'])
    print("Done edge sampling")

    # set node/edge feature
    node_id = torch.from_numpy(node_id).view(-1, 1)
    edge_type = torch.from_numpy(edge_type)
    node_norm = torch.from_numpy(node_norm).view(-1, 1)
    data, labels = torch.from_numpy(data), torch.from_numpy(labels)
    deg = g.in_degrees(range(g.number_of_nodes())).float().view(-1, 1)
    if use_cuda:
        node_id, deg = node_id.cuda(), deg.cuda()
        edge_type, node_norm = edge_type.cuda(), node_norm.cuda()
        data, labels = data.cuda(), labels.cuda()
    g.ndata.update({'id': node_id, 'norm': node_norm})
    g.edata['type'] = edge_type

    t0 = time.time()
    loss = model.get_loss(g, data, labels)
    t1 = time.time()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), args['grad_norm']) # clip gradients
    optimizer.step()
    t2 = time.time()

    forward_time.append(t1 - t0)
    backward_time.append(t2 - t1)
    loss_values.append(loss.item())
    print("Epoch {:04d} | Loss {:.4f} | Best MRR {:.4f} | Forward {:.4f}s | Backward {:.4f}s".
          format(epoch, loss.item(), best_mrr, forward_time[-1], backward_time[-1]))

    optimizer.zero_grad()

    # validation
    if epoch % args['evaluate_every'] == 0:
        # perform validation on CPU because full graph is too large
        if use_cuda:
            model.cpu()
        model.eval()
        print("start eval")
        mrr = evaluate(test_graph, model, valid_data, num_nodes,
                             hits=[1, 3, 10], eval_bz=args['eval_batch_size'])
        # save best model
        if mrr < best_mrr:
            if epoch >= args['n_epochs']:
                break
        else:
            best_mrr = mrr
            torch.save({'state_dict': model.state_dict(), 'epoch': epoch},
                       model_state_file)
        if use_cuda:
            model.cuda()

print("training done")
train_done = time.time()
print("Mean forward time: {:4f}s".format(np.mean(forward_time)))
print("Mean Backward time: {:4f}s".format(np.mean(backward_time)))
print("Training time: {:4f}min").format((train_done - train_start)/60)

print("\nstart testing:")
# use best model checkpoint
checkpoint = torch.load(model_state_file)
if use_cuda:
    model.cpu() # test on CPU
model.eval()
model.load_state_dict(checkpoint['state_dict'])
print("Using best epoch: {}".format(checkpoint['epoch']))
evaluate(test_graph, model, test_data, num_nodes, hits=[1, 3, 10],
               eval_bz=args['eval_batch_size'])

# Print loss values
plt.plot(loss_values)
plt.show()

# entities: 14541
# relations: 237
# edges: 272115
Test graph:
g._in_degrees
<bound method DGLBaseGraph.in_degrees of DGLGraph(num_nodes=14541, num_edges=544230,
         ndata_schemes={}
         edata_schemes={})>
g.number_of_nodes
14541
in_deg
[ 10.  20. 245. ...  21.  34.  35.]
14541
norm
[0.1        0.05       0.00408163 ... 0.04761905 0.02941176 0.02857143]
# nodes: 14541, # edges: 544230


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:171: RuntimeWarning: divide by zero encountered in true_divide


start training...
# sampled nodes: 2268
# sampled edges: 3000
g._in_degrees
<bound method DGLBaseGraph.in_degrees of DGLGraph(num_nodes=2268, num_edges=3000,
         ndata_schemes={}
         edata_schemes={})>
g.number_of_nodes
2268
in_deg
[3. 1. 0. ... 0. 1. 1.]
2268
norm
[0.33333334 1.         0.         ... 0.         1.         1.        ]
# nodes: 2268, # edges: 3000
Done edge sampling


/usr/local/lib/python3.6/dist-packages/dgl/base.py:18: UserWarning: Initializer is not set. Use zero initializer instead. To suppress this warning, use `set_initializer` to explicitly specify which initializer to use.
  warnings.warn(msg)


Epoch 0001 | Loss 2.2153 | Best MRR 0.0000 | Forward 0.0257s | Backward 0.3210s
# sampled nodes: 2182
# sampled edges: 3000
g._in_degrees
<bound method DGLBaseGraph.in_degrees of DGLGraph(num_nodes=2182, num_edges=3000,
         ndata_schemes={}
         edata_schemes={})>
g.number_of_nodes
2182
in_deg
[2. 3. 0. ... 0. 1. 1.]
2182
norm
[0.5        0.33333334 0.         ... 0.         1.         1.        ]
# nodes: 2182, # edges: 3000
Done edge sampling
Epoch 0002 | Loss 3.8559 | Best MRR 0.0000 | Forward 0.0107s | Backward 0.2823s
# sampled nodes: 2294
# sampled edges: 3000
g._in_degrees
<bound method DGLBaseGraph.in_degrees of DGLGraph(num_nodes=2294, num_edges=3000,
         ndata_schemes={}
         edata_schemes={})>
g.number_of_nodes
2294
in_deg
[1. 0. 2. ... 1. 0. 0.]
2294
norm
[1.  0.  0.5 ... 1.  0.  0. ]
# nodes: 2294, # edges: 3000
Done edge sampling
Epoch 0003 | Loss 5.8978 | Best MRR 0.0000 | Forward 0.0100s | Backward 0.2703s
# sampled nodes: 2285
# sampled edges: 3000
g.

RuntimeError: ignored